name: Laravel CI

on:
  push:
    branches:
      - main
      - develop
      - feature/product-api

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test